### PR TITLE
fix: null context crash

### LINKED ISSUE #3239: FlutterError - Null check operator used on a null value
ios:

https://console.firebase.google.com/u/0/project/based-hardware/crashlytics/app/ios:com.friend-app-with-wearable.ios12/issues/9d8c722b4fb6536e059d42096c03b31d?time=7d&types=crash&sessionEventKey=fadd2e6bd77a4e5c88f5cc4cbf5c13f3_2140403591028161253

logs:

```
          Fatal Exception: FlutterError
0  ???                            0x0 State.setState + 1219 (framework.dart:1219)
1  ???                            0x0 MemoriesPageState._filterByCategory + 216 (page.dart:216)
2  ???                            0x0 MemoriesPageState._applyFilter.<fn> + 200 (page.dart:200)
3  ???                            0x0 State.setState + 1199 (framework.dart:1199)
4  ???                            0x0 MemoriesPageState._applyFilter + 195 (page.dart:195)
5  ???                            0x0 MemoriesPageState.initState.<fn> + 176 (page.dart:176)
```

---

android:

https://console.firebase.google.com/u/0/project/based-hardware/crashlytics/app/android:com.friend.ios/issues/ed2f28a702a8b4699cc2de5a316ef06e?time=7d&types=crash&sessionEventKey=68F17BE3004D0001775F8252BF0C135A_2140407636035358369

logs:

```
          Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Null check operator used on a null value
       at State.setState(framework.dart:1219)
       at MemoriesPageState._filterByCategory(page.dart:216)
       at MemoriesPageState._applyFilter.<fn>(page.dart:200)
       at State.setState(framework.dart:1199)
       at MemoriesPageState._applyFilter(page.dart:195)
       at MemoriesPageState.initState.<fn>(page.dart:176)
```

### PR DESCRIPTION
**Pull request by krushnarout**
closes #3239

### CODE REVIEW

File: app/lib/pages/memories/page.dart [hunk 1]
```diff
@@ -215,10 +215,17 @@ class MemoriesPageState extends State<MemoriesPage> with AutomaticKeepAliveClien
...
 
   void _filterByCategory(MemoryCategory? category) {
+    if (!mounted) return;
+
     setState(() {
       _selectedCategory = category;
     });
-    context.read<MemoriesProvider>().setCategoryFilter(category);
+
+    WidgetsBinding.instance.addPostFrameCallback((_) {
```
Comment (mdmohsin7) [inline app/lib/pages/memories/page.dart]: I don't think this will ever get called when the widget is not mounted because we return early, so not really required to add the post frame callback coz there will never be a frame rebuild (when not mounted)

**Review by mdmohsin7 — COMMENTED** [review]
Not a big thing or that important, but good to follow,  use `addPostFrameCallback` but never abuse it haha
