### PR TITLE
fix: null check operator used on a null value

### LINKED ISSUE #3307: FlutterError - Null check operator used on a null value
Provider._inheritedElementOf

https://console.firebase.google.com/u/0/project/based-hardware/crashlytics/app/ios:com.friend-app-with-wearable.ios12/issues/a8c821212ea690bd4ecf96e4a9d696c9?time=7d&types=crash&sessionEventKey=0d36adc4c6b6430b9279f909ac5fdbf7_2145110791861541266

logs:

```
          Fatal Exception: FlutterError
0  ???                            0x0 Element.widget + 3598 (framework.dart:3598)
1  ???                            0x0 Provider._inheritedElementOf + 377 (provider.dart:377)
2  ???                            0x0 Provider.of + 327 (provider.dart:327)
3  ???                            0x0 ReadContext.read + 683 (provider.dart:683)
4  ???                            0x0 AppListItem.build.<fn>.<fn> + 39 (list_item.dart:39)
```

### PR DESCRIPTION
**Pull request by krushnarout**
closes #3307

### CODE REVIEW

File: app/lib/pages/apps/list_item.dart [hunk 1]
```diff
@@ -24,19 +24,22 @@ class AppListItem extends StatelessWidget {
...
         return (enabled: app.enabled, isLoading: isLoading);
       },
       builder: (context, state, child) {
         return GestureDetector(
           onTap: () async {
             MixpanelManager().pageOpened('App Detail');
+            final appProvider = context.read<AppProvider>();
             await routeToPage(context, AppDetailPage(app: app));
-            context.read<AppProvider>().setApps();
+            appProvider.setApps();
```
Comment (mdmohsin7) [inline app/lib/pages/apps/list_item.dart]: I think calling setApps anyway is unnecessary, can you pls check what it does and why it needs to be called here? if it's not suitable here and then just remove this call (don't think makes much sense cause it's called after navigating)

Comment (krushnarout) [reply app/lib/pages/apps/list_item.dart]: Yeah, it wasn’t needed. I’ve removed it

**Comment by beastoin** [comment]
what is the cause? and why does this fix help?

@krushnarout

**Comment by krushnarout** [comment]
> what is the cause?

`context.read()` was called after async navigation, so context got disposed and caused a null crash.

>why does this fix help?

I've removed post navigation call.

 Improvement:
 
I've changed from using `context.read<AppProvider>()` multiple times to storing it once in `final appProvider = context.read<AppProvider>();`
 
 @beastoin

**Comment by beastoin** [comment]
lgtm @krushnarout
