### PR TITLE
fix: google play review popup

### LINKED ISSUE #2888: rate on google play popup doesnt lead to google play to rate when clicked
on android (pixel), i got rate popup when checked action item but nothing happened when clicked, only popup closed but no redirect to play store for rating

### PR DESCRIPTION
**Pull request by krushnarout**
closes #2888 

https://github.com/user-attachments/assets/c8f7b6b6-2b7a-4c6e-b2d4-241184a6c7bd

### CODE REVIEW

File: app/lib/services/app_review_service.dart [hunk 1]
```diff
@@ -159,18 +160,29 @@ class AppReviewService {
...
+                            }
                           } else {
-                            await _inAppReview.openStoreListing(
-                              appStoreId: Platform.isIOS ? '6651027111' : null,
-                            );
-                            MixpanelManager()
-                                .track('App Store Opened', properties: {'source': 'action_item_completion'});
+                            // Open Play Store
+                            final Uri playStoreUrl =
+                                Uri.parse('https://play.google.com/store/apps/details?id=com.friend.ios');
```
Comment (mdmohsin7) [inline app/lib/services/app_review_service.dart]: maybe move this to the _inAppReview service itself just like openStoreListing

File: app/lib/services/app_review_service.dart [hunk 2]
```diff
@@ -159,18 +160,29 @@ class AppReviewService {
...
-                                .track('App Review Requested', properties: {'source': 'action_item_completion'});
+                          if (Platform.isIOS) {
+                            // Use in-app review for iOS
+                            if (await _inAppReview.isAvailable()) {
+                              await _inAppReview.requestReview();
+                              MixpanelManager()
+                                  .track('App Review Requested');
+                            } else {
+                              await _inAppReview.openStoreListing(
+                                appStoreId: '6651027111',
```
Comment (mdmohsin7) [inline app/lib/services/app_review_service.dart]: I think you can just hardcode the appStoreId in the _inAppReview service itself because it will never change

**Comment by krushnarout** [comment]
@mdmohsin7 done
