### PR TITLE
fix conversation grouping null crash

### LINKED ISSUE #3764: FlutterError - Null check operator used on a null value
ConversationProvider.getConversationDateAndIndex
FlutterError - Null check operator used on a null value

ios:

https://console.firebase.google.com/u/0/project/based-hardware/crashlytics/app/ios:com.friend-app-with-wearable.ios12/issues/c3226f7e451ecd0c359600fed792d01b?time=7d&types=crash&sessionEventKey=d2d928fd4de4496e8b9c15e71618720c_2162135951255972630

logs:

```
          Fatal Exception: FlutterError
0  ???                            0x0 ConversationProvider.getConversationDateAndIndex + 706 (conversation_provider.dart:706)
1  ???                            0x0 _ConversationDetailPageState.initState.<fn> + 170 (page.dart:170)
2  ???                            0x0 SchedulerBinding._invokeFrameCallback + 1434 (binding.dart:1434)
3  ???                            0x0 SchedulerBinding.handleDrawFrame + 1361 (binding.dart:1361)
4  ???                            0x0 SchedulerBinding._handleDrawFrame + 1200 (binding.dart:1200)
```

android:

https://console.firebase.google.com/u/0/project/based-hardware/crashlytics/app/android:com.friend.ios/issues/ca5f46acf1c87309996ef43104880416?time=7d&types=crash&sessionEventKey=693D94F90132000222D2AF3F0C957257_2161882818115144296

logs:

```
          Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Null check operator used on a null value
       at ConversationProvider.getConversationDateAndIndex(conversation_provider.dart:657)
       at _ConversationDetailPageState.initState.<fn>(page.dart:170)
       at SchedulerBinding._invokeFrameCallback(binding.dart:1434)
       at SchedulerBinding.handleDrawFrame(binding.dart:1361)
       at SchedulerBinding._handleDrawFrame(binding.dart:1200)
```

### PR DESCRIPTION
**Pull request by krushnarout**
closes #3764

### CODE REVIEW

File: app/lib/pages/conversation_detail/page.dart [hunk 1]
```diff
@@ -161,16 +161,27 @@ class _ConversationDetailPageState extends State<ConversationDetailPage> with Ti
...
-      var conversationProvider = Provider.of<ConversationProvider>(context, listen: false);
+      if (!mounted) return;
+
+      final provider = Provider.of<ConversationDetailProvider>(context, listen: false);
+      final conversationProvider = Provider.of<ConversationProvider>(context, listen: false);
 
       // Ensure the provider has the conversation data from the widget parameter
       provider.setCachedConversation(widget.conversation);
 
+      conversationProvider.groupConversationsByDate();
```
Comment (mdmohsin7) [inline app/lib/pages/conversation_detail/page.dart:172]: why do we have to group them here?

Comment (krushnarout) [reply app/lib/pages/conversation_detail/page.dart:172]: so that grouped state exists before both index lookup and updates, preventing wrong indexing and null crash

Comment (beastoin) [reply app/lib/pages/conversation_detail/page.dart:172]: @mdmohsin7 man don't hesitate with @krushnarout and feel free to merge the PR once you see it's good.

**Comment by krushnarout** [comment]
@mdmohsin7 fixed conflicts, pls review thank you

**Review by mdmohsin7 — APPROVED** [review]
