### PR TITLE
Sync icon state fix

### LINKED ISSUE #1620: Download Icon State Not Refreshed After Syncing
After completing the syncing process, the download icon remains stuck and does not reflect the refreshed state. The only way to resolve this issue is to force close the app and then reopen it, which is not an ideal user experience.

Steps to Reproduce:
	1.	Sync data in the app.
	2.	Observe the download icon remains stuck even after syncing is complete.
	3.	Force close the app and reopen it to see the icon update to its correct state.

Expected Behavior:
The download icon state should automatically refresh after syncing without requiring the user to close and reopen the app.

Actual Behavior:
The icon remains in its previous state, giving the impression that syncing has not been completed.

Environment:
	•	App Version: 1.0.50+194
	
image

### PR DESCRIPTION
**Pull request by mdmohsin7**
closes #1620

### CODE REVIEW

File: app/lib/pages/home/page.dart [hunk 1]
```diff
@@ -441,17 +441,22 @@ class _HomePageState extends State<HomePage> with WidgetsBindingObserver, Ticker
...
-                            },
-                            child: Container(
-                              padding: const EdgeInsets.only(left: 12),
-                              child: const Icon(Icons.download, color: Colors.white, size: 24),
-                            ),
-                          )
-                        : const SizedBox.shrink());
+                    return Consumer2<ConversationProvider, DeviceProvider>(
+                        builder: (context, convoProvider, deviceProvider, child) {
+                      if (convoProvider.missingWalsInSeconds >= 120 && deviceProvider.connectedDevice != null) {
```
Comment (beastoin) [inline app/lib/pages/home/page.dart]: we don't need the connected device with local sync feature man @mdmohsin7

Comment (mdmohsin7) [reply app/lib/pages/home/page.dart]: If I don't check for the connected device, then the icon will still show up when there's no connected device. I guess Salman mentioned that it should not show up or I might be wrong, have to check his messages once

Comment (mdmohsin7) [reply app/lib/pages/home/page.dart]: removed the check anyway

**Comment by beastoin** [comment]
lgtm @mdmohsin7 🥳

Extended question: how can we reduce the callback of https://github.com/BasedHardware/omi/pull/1624/files#diff-2ab85b8834f6a7ae24e568e9f383a1246ad7bdf8136b55b5d352e2efe1851de6R445 , does it negatively affect to UI when the mssingwalseconds increase multiple time, e.g. 121, 122, 123, 124..., and so on ?
