### PR TITLE
fix add url validation

### LINKED ISSUE #3762: FlutterError - FormatException: Scheme not starting with alphabetic character
_AppDetailPageState.build.<fn>.<fn>
FlutterError - FormatException: Scheme not starting with alphabetic character (at character 1) 

ios:

https://console.firebase.google.com/u/0/project/based-hardware/crashlytics/app/ios:com.friend-app-with-wearable.ios12/issues/e9f238e784a735c91aec6cd4a80a3bb7?time=7d&types=crash&sessionEventKey=b816769e35ac431788f832a671336a61_2162065632663219686

logs

```
          Fatal Exception: FlutterError
0  ???                            0x0 Uri.parse (dart:core)
1  ???                            0x0 _AppDetailPageState.build.<fn>.<fn> + 1405 (app_detail.dart:1405)
2  ???                            0x0 _InkResponseState.handleTap + 1204 (ink_well.dart:1204)
3  ???                            0x0 GestureRecognizer.invokeCallback + 345 (recognizer.dart:345)
4  ???                            0x0 TapGestureRecognizer.handleTapUp + 758 (tap.dart:758)
5  ???                            0x0 BaseTapGestureRecognizer._checkUp + 383 (tap.dart:383)
6  ???                            0x0 BaseTapGestureRecognizer.acceptGesture + 353 (tap.dart:353)
7  ???                            0x0 GestureArenaManager.sweep + 173 (arena.dart:173)
8  ???                            0x0 GestureBinding.handleEvent + 532 (binding.dart:532)
9  ???                            0x0 GestureBinding.dispatchEvent + 498 (binding.dart:498)
10 ???                            0x0 RendererBinding.dispatchEvent + 473 (binding.dart:473)
11 ???                            0x0 GestureBinding._handlePointerEventImmediately + 437 (binding.dart:437)
12 ???                            0x0 GestureBinding.handlePointerEvent + 394 (binding.dart:394)
13 ???                            0x0 GestureBinding._flushPointerEventQueue + 341 (binding.dart:341)
14 ???                            0x0 GestureBinding._handlePointerDataPacket + 308 (binding.dart:308)
```

android:

https://console.firebase.google.com/u/0/project/based-hardware/crashlytics/app/android:com.friend.ios/issues/59f6d35df899e73a1fabc4eff9f5273e?time=7d&types=crash&sessionEventKey=693EC5D0034E000104FA0C1FF224B2C5_2162165236968413353

### PR DESCRIPTION
**Pull request by krushnarout**
closes #3762

### CODE REVIEW

File: app/lib/pages/apps/app_detail/app_detail.dart [hunk 1]
```diff
@@ -241,6 +241,21 @@ class _AppDetailPageState extends State<AppDetailPage> {
     return subscription['status'] == 'active' && subscription['cancel_at_period_end'] == false;
   }
 
+  Uri? _safeParseUrl(String? raw) {
```
Comment (mdmohsin7) [inline app/lib/pages/apps/app_detail/app_detail.dart]: I think tryParse on uri does the same thing?

Comment (krushnarout) [reply app/lib/pages/apps/app_detail/app_detail.dart]: No, tryParse avoids crash

Comment (beastoin) [reply app/lib/pages/apps/app_detail/app_detail.dart]: Is this PR also trying to avoid crashes?

BTW @mdmohsin7, please help him, and then feel free to merge it once you see it is good.

Comment (mdmohsin7) [reply app/lib/pages/apps/app_detail/app_detail.dart]: tryParse internally does the same thing which you are trying to do with safeTryParse, infact a lot more and better validation. So there's no point in having a wrapper over tryParse @krushnarout 

image

Comment (krushnarout) [reply app/lib/pages/apps/app_detail/app_detail.dart]: Got it, removed...thank you
